; PlatformIO Project Configuration File (GitHub version)

[platformio]
src_dir = .

[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino

; Librairies locales (mettre ton chemin local dans le fichier local)
lib_extra_dirs = <local_path_to_libraries>

; Partitions
board_build.partitions = partitions/esp32cam_ota.csv

; OTA et upload — à remplir localement
upload_protocol = espota
upload_port = <YOUR_ESP32_IP>
upload_flags = --auth=YOUR_OTA_PASSWORD

; Monitor
monitor_speed = 115200
